FROM golang:1.26.5 AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o bin/echo-backend ./cmd/echo-backend

FROM debian:bookworm-slim
COPY --from=build /app/bin/echo-backend /echo-backend
ENTRYPOINT ["/echo-backend"]